name: CI/CD Pipeline

on:
  push:
    branches:
      - release-*
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Deploy Infrastructure
           - name: Deploy Infrastructure
        run: |
          cd infra
          npm install
          OUTPUTS=$(npx cdk deploy --require-approval never --parameters environment=${{ github.ref_name == 'main' && 'production' || 'staging' }})
          CLOUDFRONT_ID=$(echo "$OUTPUTS" | grep 'CloudFrontID' | awk '{print $NF}')
          CLOUDFRONT_URL=$(echo "$OUTPUTS" | grep 'CloudFrontURL' | awk '{print $NF}')
          echo "CLOUDFRONT_ID=$CLOUDFRONT_ID" >> $GITHUB_ENV
          echo "CLOUDFRONT_URL=$CLOUDFRONT_URL" >> $GITHUB_ENV
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}


      # Step 4: Build React App
      - name: Build React App
        run: |
          npm install --prefix rick-morty-app-client
          npm run build --prefix rick-morty-app-client

      # Step 5: Deploy React Build to S3
      - name: Deploy React Build to S3
        run: |
          aws s3 sync rick-morty-app-client/build s3://${{ github.ref_name == 'main' && 'rick-morty-bucket-production' || 'rick-morty-bucket-staging' }} --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      # Step 6: Invalidate CloudFront Cache
      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      # Step 7: Output CloudFront URL
      - name: Output CloudFront URL
        run: |
          echo "CloudFront URL: $CLOUDFRONT_ID"
